INSERT INTO `inventory_financial_book`
(`id`, `order_unit_no_from`, `order_unit_no_to`, `store_no`, `company_no`, `order_unit_no`, `item_no`, `item_code`, `item_name`, `brand_no`, `category_no`, `sku_no`, `size_no`, `bill_no`, `status`, `bill_type`, `in_out_flag`, `biz_type`, `account_type`, `bill_date`, `cost`, `balance_offset`, `factory_in_offset`, `factory_in_diff_offset`, `transit_in_offset`, `transit_out_offset`, `in_diff_offset`, `out_diff_offset`, `transit_in_account_offset`, `transit_out_account_offset`, `in_diff_account_offset`, `out_diff_account_offset`, `lock_offset`, `occupied_offset`, `backup_offset`, `guest_bad_offset`, `original_bad_offset`, `bad_transit_offset`, `bad_diff_offset`, `create_time`, `create_timestamp`, `update_time`, `sharding_flag`, `ref_bill_no`, `ref_bill_type`, `finance_type`)
VALUES
    ('fa163e84da8011ec532ab55ac03cba99', '', 'Z330', 'Z3003', NULL, 'Z330', '20210827000222', 'T2134ZP18A1', '小恐龙帆布袋', 'XM01', '010102', '920210902000991', '35', 'Z3003IC211202000006', 5, 1304, 1, 0, 2, '2021-12-02', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '2021-12-02 12:46:02', '2021-12-02 12:46:02.103', '2021-12-02 12:46:02', 'U010101_Z3', 'Z330DA211100159', 1301, 0);




CREATE TABLE `inventory_financial_book` (
                                            `id` char(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '流水号',
                                            `order_unit_no_from` char(18) DEFAULT '' COMMENT '发方订货单位编码',
                                            `order_unit_no_to` char(18) DEFAULT '' COMMENT '收方订货单位编码',
                                            `store_no` char(18) DEFAULT '' COMMENT '机构编码',
                                            `company_no` char(18) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '公司编码',
                                            `order_unit_no` char(18) NOT NULL DEFAULT '' COMMENT '订货单位',
                                            `item_no` char(18) DEFAULT '' COMMENT '商品编码',
                                            `item_code` varchar(30) DEFAULT '' COMMENT '商品编码(出厂时的商品编码)',
                                            `item_name` char(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '商品名称',
                                            `brand_no` char(18) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '品牌编码',
                                            `category_no` char(18) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '类别编码',
                                            `sku_no` char(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'sku码',
                                            `size_no` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '尺寸编码',
                                            `bill_no` char(30) NOT NULL DEFAULT '' COMMENT '单据编码',
                                            `status` tinyint(3) DEFAULT '0' COMMENT '单据状态 1-已发未收（出库）；2-已收货（入库）',
                                            `bill_type` int(11) NOT NULL DEFAULT '0' COMMENT '单据类型',
                                            `in_out_flag` tinyint(3) NOT NULL DEFAULT '0' COMMENT '出入库标志（-1：出库 1：入库）,-50-完结、释放,-20-销售出库/仓出店(备货)/店退残（客残出店）,-5-团购出库单/批发出库单/区内差异调整/原残移仓,-4-区内差异调整(验收自动产生),-3-跨区差异生成调货入库单,-2-盘差单(冻结),0-差异处理,2-跨区分批（出）差异处理,7-未使用,9-未使用,50-值与注释不同,100-值与注释不同,125-值与注释不同,126-值与注释不同',
                                            `biz_type` int(11) DEFAULT '0' COMMENT '单据的业务类型',
                                            `account_type` tinyint(3) DEFAULT '0' COMMENT '0:记非实物库存、1：记实物库存,-1-店退残,2-差异处理',
                                            `bill_date` date NOT NULL DEFAULT '2000-01-01' COMMENT '业务发生日期',
                                            `cost` decimal(12,2) DEFAULT '0.00' COMMENT '含税单价',
                                            `balance_offset` int(11) DEFAULT '0' COMMENT '正品库存发生量',
                                            `factory_in_offset` int(11) DEFAULT '0' COMMENT '厂入库在途变化量',
                                            `factory_in_diff_offset` int(11) DEFAULT '0' COMMENT '厂入库在途差异变化量',
                                            `transit_in_offset` int(11) DEFAULT '0' COMMENT '内区入库在途变化量',
                                            `transit_out_offset` int(11) DEFAULT '0' COMMENT '内区出库在途变化量',
                                            `in_diff_offset` int(11) DEFAULT '0' COMMENT '内区入库差异变化量',
                                            `out_diff_offset` int(11) DEFAULT '0' COMMENT '内区出库差异变化量',
                                            `transit_in_account_offset` int(11) DEFAULT '0' COMMENT '外区入库在途变化量',
                                            `transit_out_account_offset` int(11) DEFAULT '0' COMMENT '外区出库在途变化量',
                                            `in_diff_account_offset` int(11) DEFAULT '0' COMMENT '外区入库差异变化量',
                                            `out_diff_account_offset` int(11) DEFAULT '0' COMMENT '外区出库差异变化量',
                                            `lock_offset` int(11) DEFAULT '0' COMMENT '冻结变化量',
                                            `occupied_offset` int(11) DEFAULT '0' COMMENT '预占变化量',
                                            `backup_offset` int(11) DEFAULT '0' COMMENT '备货变化量',
                                            `guest_bad_offset` int(11) DEFAULT '0' COMMENT '客残变化量',
                                            `original_bad_offset` int(11) DEFAULT '0' COMMENT '原残变化量',
                                            `bad_transit_offset` int(11) DEFAULT '0' COMMENT '次品在途发生量',
                                            `bad_diff_offset` int(11) DEFAULT '0' COMMENT '次品在途差异变化',
                                            `create_time` datetime NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '记账时间',
                                            `create_timestamp` datetime(3) DEFAULT '2000-01-01 00:00:00.000' COMMENT '时间戳',
                                            `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                            `sharding_flag` char(20) DEFAULT '' COMMENT '分库字段：本部+大区',
                                            `ref_bill_no` varchar(200) DEFAULT '' COMMENT '相关单据编码',
                                            `ref_bill_type` int(11) DEFAULT '0' COMMENT '相关单据类型',
                                            `finance_type` tinyint(3) NOT NULL DEFAULT '0' COMMENT 'FAS的业务类型.0:正常单.1:代销单',
                                            PRIMARY KEY (`id`),
                                            KEY `idx_inner_group` (`order_unit_no_from`,`order_unit_no_to`,`item_no`),
                                            KEY `idx_ou_cost` (`sharding_flag`,`bill_date`,`order_unit_no`,`store_no`,`bill_type`,`in_out_flag`),
                                            KEY `idx_test_billDate` (`bill_type`,`in_out_flag`),
                                            KEY `IDX_brand_no` (`brand_no`),
                                            KEY `idx_inner_group_brandANDcategory` (`order_unit_no_from`,`order_unit_no_to`,`brand_no`,`category_no`),
                                            KEY `idx_bill_no_sku` (`bill_no`,`sku_no`),
                                            KEY `idx_item_no` (`item_no`),
                                            KEY `idx_ifb_brand_bill` (`brand_no`,`order_unit_no`,`bill_date`),
                                            KEY `index_update_time` (`update_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品库存台账(财务用)'